name: MacOS Release

on:
  push:
    tags:
      - "flower/v*"

jobs:
  build:
    permissions:
      contents: write

    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: 1.22.5
      - run: go version

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails (MacOS)
        working-directory: desktop
        run: wails build -platform darwin/universal

      - name: Prepare binaries for upload
        run: |
          mkdir bin
          mv desktop/build/bin/flower.app/Contents/MacOS/flower bin/flower_macos
          chmod +x bin/*

      - name: Import Code Signing Certificates for MacOS
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: MacOS download gon for code signing and app notarization
        run: |
          brew install Bearer/tap/gon

      - name: Create gon config file
        run: |
          echo '${{ secrets.GON_CONFIG }}' > gon-sign.json

      - name: Sign MacOS binary
        run: gon -log-level=info ./gon-sign.json

      - name: Clean up gon config file
        run: rm gon-sign.json

      - uses: actions/upload-artifact@v4
        with:
          name: wails-binaries-macos
          path: desktop/build/bin/*

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: desktop/build/bin/*
